services:
    redis:
        image: redis:latest
        container_name: gramio-storage-redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    redis-data:
